//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto01Fabio
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public int idStudent { get; set; }
        public string typeDocumentStudent { get; set; }
        public int documentStudent { get; set; }
        public int codeStudent { get; set; }
        public string nameStudent { get; set; }
        public string lastNameStudent { get; set; }
        public string genderStudent { get; set; }
        public string emailStudent { get; set; }
        public int phoneStudent { get; set; }
    }
}
